controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

admin_api:
    resource: ../../src/Controller/Api/Admin/
    type: annotation
    prefix: /api/admin

api_v1:
    resource: ../../src/Controller/Api/Client/V1/
    type: annotation
    prefix: /api/v1

